version: '3'
volumes:
  postgres_data: {}
  redis_data: {}
  public_assets: {}
services:
  app:
    build:
      context: .
    image: homeland_app
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - public_assets:/var/www/homeland/public/assets
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - public_assets:/var/www/homeland/public/assets