version: '3'

volumes:
  postgres_data:
  redis_data:
  es_data:

services:
  app:
    build:
      context: .
    image: homeland_app
    depends_on:
      - db
      - redis
      - es
    ports:
      - 3000:3000
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  es:
    image: elasticsearch:7.3.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    # depends_on:
    #   - db
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: homeland_web
    depends_on:
      - app
    ports:
      - 80:80
