version: '3'
volumes:
  postgres_data: {}
  redis_data: {}
services:
  app:
    build:
      context: .
    depends_on:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80