version: '3'
volumes:
  postgres_data: {}
  redis_data: {}
  bundler_gems: {}
services:
  app:
    build:
      context: .
    image: homeland_app
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    volumes:
      - bundler_gems:/usr/local/bundle
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: homeland_web
    depends_on:
      - app
    ports:
      - 80:80
