production: &defaults
  adapter: redis
  url: <%= ENV["REDIS_URL"] || "redis://redis:6379/1"  %>
  timeout: 1

development:
  <<: *defaults
  url: <%= ENV["REDIS_URL"] || "redis://redis:6379/2"  %>

test:
  <<: *defaults
  url: <%= ENV["REDIS_URL"] || "redis://redis:6379/3"  %>
